# Generated by Django 3.2.6 on 2021-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210812_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
